pipeline {
  agent any
  stages {
    stage('Clone') {
      steps {
        git 'https://github.com/1504raghavnama/SmartMessX.git'
      }
    }

    stage('Install Backend') {
      steps {
        dir('backend') {
          sh 'npm install'
        }
      }
    }

    stage('Install Frontend') {
      steps {
        dir('frontend') {
          sh 'npm install'
        }
      }
    }

    stage('Build Frontend') {
      steps {
        dir('frontend') {
          sh 'npm run build'
        }
      }
    }

    stage('Docker Build & Deploy') {
      steps {
        dir('devops') {
          sh 'docker-compose down || true'
          sh 'docker-compose up --build -d'
        }
      }
    }

    stage('Health Check') {
      steps {
        sh 'sleep 5 && curl -f http://localhost:5000/api/health || exit 1'
      }
    }
  }

  post {
    success {
      echo 'SmartMessX deployed successfully!'
    }
    failure {
      echo 'Pipeline failed. Check logs.'
    }
  }
}